apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: myekscluster
  region: ap-south-1

nodeGroups:
   - name: ngeks1
     desiredCapacity: 2
     instanceType: t2.micro
     ssh:
        publicKeyName: mykey2
   - name: ngeks2
     desiredCapacity: 1
     instanceType: t2.small
     ssh:
        publicKeyName: mykey2